import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:printing/printing.dart';
import 'accounting_engine.dart';
import 'database.dart';
import 'models.dart';
import 'pdf_service.dart';
import 'daily_position_page.dart';

void main()=>runApp(const FinanceApp());
class FinanceApp extends StatelessWidget { const FinanceApp({super.key}); @override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Finanzas Definitiva',theme:ThemeData(colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xff164e63),brightness:Brightness.light),useMaterial3:true,cardTheme:const CardThemeData(elevation:0,margin:EdgeInsets.symmetric(vertical:5))),home:const HomePage()); }

class HomePage extends StatefulWidget { const HomePage({super.key}); @override State<HomePage> createState()=>_HomePageState(); }
class _HomePageState extends State<HomePage>{ int index=0; int revision=0; void refresh(){setState(()=>revision++);} @override Widget build(BuildContext context){final pages=[Dashboard(key:ValueKey('d$revision')),Journal(key:ValueKey('j$revision'),onChanged:refresh),Reports(key:ValueKey('r$revision')),AccountsPage(key:ValueKey('a$revision')),SettingsPage(onChanged:refresh)];return Scaffold(body:SafeArea(child:pages[index]),bottomNavigationBar:NavigationBar(selectedIndex:index,onDestinationSelected:(v)=>setState(()=>index=v),destinations:const [NavigationDestination(icon:Icon(Icons.dashboard_outlined),selectedIcon:Icon(Icons.dashboard),label:'Inicio'),NavigationDestination(icon:Icon(Icons.receipt_long_outlined),label:'Diario'),NavigationDestination(icon:Icon(Icons.assessment_outlined),label:'Estados'),NavigationDestination(icon:Icon(Icons.account_tree_outlined),label:'Cuentas'),NavigationDestination(icon:Icon(Icons.settings_outlined),label:'Ajustes')]));}}

class Dashboard extends StatelessWidget{const Dashboard({super.key});Future<_Data> load()async{final db=AppDatabase.instance;return _Data(await db.accounts(),await db.transactions(),await db.setting('company'),await db.setting('currency'));}@override Widget build(BuildContext c)=>FutureBuilder<_Data>(future:load(),builder:(c,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());final d=s.data!,e=AccountingEngine(),b=e.trialBalance(d.accounts,d.txs),income=e.incomeStatement(b),bs=e.balanceSheet(b);double total(String k)=>bs[k]!.last.amount;final net=income.last.amount;return ListView(padding:const EdgeInsets.all(18),children:[Text(d.company,style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),const Text('Resumen financiero',style:TextStyle(color:Colors.blueGrey)),const SizedBox(height:16),Wrap(spacing:10,runSpacing:10,children:[Kpi('Utilidad neta',net,d.currency,Icons.trending_up),Kpi('Activos',total('Activos'),d.currency,Icons.account_balance_wallet),Kpi('Pasivos',total('Pasivos'),d.currency,Icons.payments_outlined),Kpi('Patrimonio',total('Patrimonio')+net,d.currency,Icons.savings_outlined)]),const SizedBox(height:14),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const DailyPositionPage())),icon:const Icon(Icons.today),label:const Text('Ver posición diaria'))),const SizedBox(height:18),const Text('Comprobaciones',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),CheckTile('Débitos = Créditos',b.fold<double>(0,(s,x)=>s+x.debit),b.fold<double>(0,(s,x)=>s+x.credit)),CheckTile('Activos = Pasivos + Patrimonio',total('Activos'),total('Pasivos')+total('Patrimonio')+net),const SizedBox(height:14),Card(color:const Color(0xffecfeff),child:Padding(padding:const EdgeInsets.all(16),child:Text(d.txs.isEmpty?'Aún no hay transacciones. Entra en Diario y pulsa + para registrar el primer asiento.':'Hay ${d.txs.length} transacciones registradas. Todos los estados se actualizan automáticamente.')))]);});}
class Kpi extends StatelessWidget{final String t,c;final double v;final IconData i;const Kpi(this.t,this.v,this.c,this.i,{super.key});@override Widget build(BuildContext x)=>SizedBox(width:(MediaQuery.sizeOf(x).width-48)/2,child:Card(color:const Color(0xfff0f9ff),child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(i,color:const Color(0xff0369a1)),const SizedBox(height:10),Text(t),Text('$c ${v.toStringAsFixed(2)}',style:const TextStyle(fontWeight:FontWeight.bold,fontSize:17))]))));}
class CheckTile extends StatelessWidget{final String t;final double a,b;const CheckTile(this.t,this.a,this.b,{super.key});@override Widget build(BuildContext c){final ok=(a-b).abs()<.01;return ListTile(contentPadding:EdgeInsets.zero,leading:Icon(ok?Icons.check_circle:Icons.warning,color:ok?Colors.green:Colors.orange),title:Text(t),subtitle:Text('${a.toStringAsFixed(2)} / ${b.toStringAsFixed(2)}'));}}

class Journal extends StatefulWidget{final VoidCallback onChanged;const Journal({super.key,required this.onChanged});@override State<Journal> createState()=>_JournalState();}
class _JournalState extends State<Journal>{Future<List<JournalTransaction>> load()=>AppDatabase.instance.transactions();@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Libro diario')),floatingActionButton:FloatingActionButton.extended(onPressed:()async{final ok=await Navigator.push<bool>(c,MaterialPageRoute(builder:(_)=>const TransactionForm()));if(ok==true){setState((){});widget.onChanged();}},icon:const Icon(Icons.add),label:const Text('Asiento')),body:FutureBuilder<List<JournalTransaction>>(future:load(),builder:(c,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());if(s.data!.isEmpty)return const Center(child:Text('No hay asientos registrados.'));return ListView.builder(padding:const EdgeInsets.all(12),itemCount:s.data!.length,itemBuilder:(c,i){final t=s.data![i];final amount=t.lines.fold<double>(0,(x,l)=>x+l.debit);return Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.receipt_long)),title:Text(t.description),subtitle:Text('${DateFormat('dd/MM/yyyy').format(t.date)} · ${t.cashFlowClass} · ${t.lines.length} líneas'),trailing:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(amount.toStringAsFixed(2),style:const TextStyle(fontWeight:FontWeight.bold)),IconButton(icon:const Icon(Icons.delete_outline,size:20),onPressed:()async{await AppDatabase.instance.deleteTransaction(t.id!);setState((){});widget.onChanged();})])));});}));}}

class TransactionForm extends StatefulWidget{const TransactionForm({super.key});@override State<TransactionForm>createState()=>_TransactionFormState();}
class _TransactionFormState extends State<TransactionForm>{final desc=TextEditingController(),ref=TextEditingController();DateTime date=DateTime.now();String cls='operating';List<Account> accounts=[];final lines=<Map<String,dynamic>>[{'account':null,'debit':'','credit':''},{'account':null,'debit':'','credit':''}];@override void initState(){super.initState();AppDatabase.instance.accounts().then((v)=>setState(()=>accounts=v));}double n(dynamic x)=>double.tryParse('$x'.replaceAll(',',''))??0;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Nuevo asiento')),body:ListView(padding:const EdgeInsets.all(16),children:[TextField(controller:desc,decoration:const InputDecoration(labelText:'Descripción',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:ref,decoration:const InputDecoration(labelText:'Referencia / factura',border:OutlineInputBorder())),const SizedBox(height:10),DropdownButtonFormField(value:cls,decoration:const InputDecoration(labelText:'Clasificación de efectivo',border:OutlineInputBorder()),items:const [DropdownMenuItem(value:'operating',child:Text('Operativa')),DropdownMenuItem(value:'investing',child:Text('Inversión')),DropdownMenuItem(value:'financing',child:Text('Financiamiento')),DropdownMenuItem(value:'noncash',child:Text('Sin efectivo'))],onChanged:(v)=>setState(()=>cls=v!)),const SizedBox(height:16),const Text('Débitos y créditos',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),...List.generate(lines.length,(i)=>Card(child:Padding(padding:const EdgeInsets.all(10),child:Column(children:[DropdownButtonFormField<int>(value:lines[i]['account'],isExpanded:true,decoration:const InputDecoration(labelText:'Cuenta'),items:accounts.map((a)=>DropdownMenuItem(value:a.id,child:Text('${a.code} · ${a.name}'))).toList(),onChanged:(v)=>lines[i]['account']=v),Row(children:[Expanded(child:TextFormField(key:ValueKey('d$i'),keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Débito'),onChanged:(v)=>lines[i]['debit']=v)),const SizedBox(width:12),Expanded(child:TextFormField(key:ValueKey('c$i'),keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Crédito'),onChanged:(v)=>lines[i]['credit']=v))])]))),TextButton.icon(onPressed:()=>setState(()=>lines.add({'account':null,'debit':'','credit':''})),icon:const Icon(Icons.add),label:const Text('Añadir línea')),FilledButton.icon(onPressed:()async{try{final tx=JournalTransaction(date:date,description:desc.text,reference:ref.text,cashFlowClass:cls,lines:lines.map((l)=>JournalLine(accountId:l['account']??-1,debit:n(l['debit']),credit:n(l['credit']))).toList());await AppDatabase.instance.addTransaction(tx);if(c.mounted)Navigator.pop(c,true);}catch(e){if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text('$e')));}},icon:const Icon(Icons.save),label:const Text('Guardar asiento'))]));}}

class Reports extends StatelessWidget{const Reports({super.key});Future<_Data> load()async{final db=AppDatabase.instance;return _Data(await db.accounts(),await db.transactions(),await db.setting('company'),await db.setting('currency'));}@override Widget build(BuildContext c)=>FutureBuilder<_Data>(future:load(),builder:(c,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());final d=s.data!,e=AccountingEngine(),b=e.trialBalance(d.accounts,d.txs),inc=e.incomeStatement(b),bs=e.balanceSheet(b),cash=e.cashFlow(d.accounts,d.txs),eq=e.equityStatement(b);final reports=<String,List<ReportRow>>{'Estado de Resultados':inc,'Balance General':[...bs['Activos']!,...bs['Pasivos']!,...bs['Patrimonio']!,ReportRow('RESULTADO DEL PERÍODO',inc.last.amount,total:true)],'Flujo de Efectivo':cash,'Cambios en el Patrimonio':eq,'Balance de Comprobación':b.where((x)=>x.debit!=0||x.credit!=0).map((x)=>ReportRow('${x.account.code} ${x.account.name} · D ${x.debit.toStringAsFixed(2)} / C ${x.credit.toStringAsFixed(2)}',x.signed)).toList()};return DefaultTabController(length:reports.length,child:Scaffold(appBar:AppBar(title:const Text('Estados financieros'),bottom:TabBar(isScrollable:true,tabs:reports.keys.map((x)=>Tab(text:x)).toList())),body:TabBarView(children:reports.entries.map((r)=>ReportView(title:r.key,rows:r.value,data:d)).toList())));});}
class ReportView extends StatelessWidget{final String title;final List<ReportRow> rows;final _Data data;const ReportView({super.key,required this.title,required this.rows,required this.data});@override Widget build(BuildContext c)=>Column(children:[Expanded(child:ListView(padding:const EdgeInsets.all(14),children:[Text(data.company,style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),Text(title,style:const TextStyle(fontSize:17)),const Text('Al/por el período actual'),const Divider(),...rows.map((r)=>Container(color:r.total?const Color(0xffdbeafe):null,padding:const EdgeInsets.symmetric(horizontal:8,vertical:11),child:Row(children:[Expanded(child:Text(r.label,style:TextStyle(fontWeight:r.total?FontWeight.bold:null))),Text('${data.currency} ${r.amount.toStringAsFixed(2)}',style:TextStyle(fontWeight:r.total?FontWeight.bold:null))]))) ])),Padding(padding:const EdgeInsets.all(12),child:SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:()async{final bytes=await PdfService.report(data.company,title,'Período actual',rows,data.currency);await Printing.sharePdf(bytes:bytes,filename:'${title.replaceAll(' ','_')}.pdf');},icon:const Icon(Icons.picture_as_pdf),label:const Text('Exportar PDF'))))]);}

class AccountsPage extends StatelessWidget{const AccountsPage({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Catálogo de cuentas')),body:FutureBuilder<List<Account>>(future:AppDatabase.instance.accounts(),builder:(c,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());return ListView(children:s.data!.map((a)=>ListTile(leading:CircleAvatar(child:Text(a.code.substring(0,1))),title:Text('${a.code} · ${a.name}'),subtitle:Text('${a.type.name} / ${a.subtype}'))).toList());}));}
class SettingsPage extends StatefulWidget{final VoidCallback onChanged;const SettingsPage({super.key,required this.onChanged});@override State<SettingsPage>createState()=>_SettingsPageState();}
class _SettingsPageState extends State<SettingsPage>{final company=TextEditingController(),currency=TextEditingController();@override void initState(){super.initState();AppDatabase.instance.setting('company').then((v)=>company.text=v);AppDatabase.instance.setting('currency').then((v)=>currency.text=v);}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Configuración')),body:ListView(padding:const EdgeInsets.all(16),children:[TextField(controller:company,decoration:const InputDecoration(labelText:'Nombre de la empresa',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:currency,decoration:const InputDecoration(labelText:'Moneda (USD, EUR, CUP...)',border:OutlineInputBorder())),const SizedBox(height:12),FilledButton(onPressed:()async{await AppDatabase.instance.setSetting('company',company.text);await AppDatabase.instance.setSetting('currency',currency.text.toUpperCase());widget.onChanged();if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Configuración guardada')));},child:const Text('Guardar')),const Divider(height:40),ListTile(leading:const Icon(Icons.science_outlined),title:const Text('Cargar empresa de demostración'),subtitle:const Text('Añade un ejemplo completo para comprobar todos los estados.'),onTap:()async{await AppDatabase.instance.loadDemo();widget.onChanged();if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Ejemplo cargado')));}),ListTile(leading:const Icon(Icons.inventory_2_outlined),title:const Text('Inventario'),subtitle:const Text('Se controla mediante las cuentas y asientos del diario.')),ListTile(leading:const Icon(Icons.factory_outlined),title:const Text('Activos y depreciación'),subtitle:const Text('Registra activo, depreciación y depreciación acumulada.')),ListTile(leading:const Icon(Icons.people_outline),title:const Text('Cuentas por cobrar y pagar'),subtitle:const Text('Disponibles en el catálogo de cuentas.')),ListTile(leading:const Icon(Icons.lock_outline),title:const Text('Datos privados y offline'),subtitle:const Text('La base de datos permanece en este dispositivo.')),OutlinedButton.icon(onPressed:()async{await AppDatabase.instance.clearAll();widget.onChanged();if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Transacciones eliminadas')));},icon:const Icon(Icons.delete_forever),label:const Text('Borrar todas las transacciones'))]));}}
class _Data{final List<Account> accounts;final List<JournalTransaction> txs;final String company,currency;const _Data(this.accounts,this.txs,this.company,this.currency);}
