name: paqueteria_migrator
publish_to: 'none'
description: Migrador seguro de datos para Paqueteria.
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  cross_file: ^0.3.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
